Tidy up scripts

diff --git a/tests/css_check b/tests/css_check
--- a/tests/css_check
+++ b/tests/css_check
@@ -1,12 +1,10 @@
 #!/usr/bin/env bash
-
-set -e  # Stop script execution if error encountered
+set -e
 
 echo "Checking for CSS errors..."
-
 csslint_output=$(csslint css/current.css)
 
-if [[ $(echo "$csslint_output" | grep -c "warn" || true) -eq "0" ]]; then
+if [[ $(echo "$csslint_output" | grep -c "error" || true) -eq "0" ]]; then
   echo "No CSS errors detected by CSSLint"
   exit 0
 else
diff --git a/tests/javascript_check b/tests/javascript_check
--- a/tests/javascript_check
+++ b/tests/javascript_check
@@ -1,18 +1,13 @@
 #!/usr/bin/env bash
-
-set -e  # Stop script execution if error encountered
+set -e
 
 echo "Checking for Javascript errors..."
-
-# Grep for errors detected by JSHint
-output=$(jshint --verbose style-guide/js/sg-scripts.js | grep -E "E[0-9]+.$")
-
-if [[ $(echo "$output" | wc -l) -ge "0" ]]; then
-  echo "JSHint detected Javascript errors!"
-  # Output file with errors
-  echo "$output" > "tmp/js_errors.txt"
-  exit 1
-else
+if [[ $(jshint --verbose style-guide/js/sg-scripts.js | grep -E "E[0-9]+.$" | wc -l) -eq "0" ]]; then
   echo "No Javascript errors detected by JSHint"
   exit 0
+else
+  echo "JSHint detected Javascript errors!"
+  output=$(jshint --verbose style-guide/js/sg-scripts.js | grep -E "E[0-9]+.$")
+  echo "$output" > "tmp/js_errors.txt"
+  exit 1
 fi
