Output file if error found

diff --git a/tests/css_check b/tests/css_check
--- a/tests/css_check
+++ b/tests/css_check
@@ -1,19 +1,17 @@
 #!/usr/bin/env bash
 
-set -e
-
-set -a
-echo "Loading environment..."
-source "./.env"
-source "./.secrets"
-set +a
+set -e  # Stop script execution if error encountered
 
 echo "Checking for CSS errors..."
 
-if [[ $(csslint css/current.css | grep -c "error" || true) -eq "0" ]]; then
+csslint_output=$(csslint css/current.css)
+
+if [[ $(echo "$csslint_output" | grep -c "warn" || true) -eq "0" ]]; then
   echo "No CSS errors detected by CSSLint"
   exit 0
 else
   echo "CSSLint detected CSS errors!"
+  # Output file with errors
+  echo "$csslint_output" > "tmp/css_errors.txt"
   exit 1
 fi
diff --git a/tests/javascript_check b/tests/javascript_check
--- a/tests/javascript_check
+++ b/tests/javascript_check
@@ -1,22 +1,18 @@
 #!/usr/bin/env bash
 
-set -e
-
-set -a
-echo "Loading environment..."
-source "./.env"
-source "./.secrets"
-set +a
+set -e  # Stop script execution if error encountered
 
 echo "Checking for Javascript errors..."
 
+# Grep for errors detected by JSHint
 output=$(jshint --verbose style-guide/js/sg-scripts.js | grep -E "E[0-9]+.$")
-echo "$output" | wc -l
 
 if [[ $(echo "$output" | wc -l) -ge "0" ]]; then
   echo "JSHint detected Javascript errors!"
-  exit 0
+  # Output file with errors
+  echo "$output" > "tmp/js_errors.txt"
+  exit 1
 else
   echo "No Javascript errors detected by JSHint"
-  exit 1
+  exit 0
 fi
